#!/bin/bash

time=0
while true; do
  newtime=$(find . -regex "[^#]*.$1$" -exec stat -f "%m" \{} \; | sort -n -r | head -1)
  if [ "$newtime" -gt "$time" ]; then
    clear
    echo $2 | bash
  fi

  time=$newtime;
  sleep 1
done
